version = 0.1

[default.deploy.parameters]
stack_name = "ServerlessToDoApp"
resolve_s3 = true
s3_prefix = "ServerlessToDoApp"
region = "ap-south-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"dev\""
image_repositories = []
